site_name: aiogram Ton Connect UI
site_description: TON Connect UI for aiogram-based bots.
site_url: https://tonmendon.github.io/aiogram-tonconnect
repo_name: aiogram-tonconnect
repo_url: https://github.com/tonmendon/aiogram-tonconnect
edit_uri: https://github.com/tonmendon/aiogram-tonconnect/tree/main/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.footer
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list


nav:
  - Overview: 'index.md'
  - User Guide:
      - Getting started: 'user-guide/getting-started.md'
      - Connecting wallet: 'user-guide/connecting-wallet.md'
      - Sending transactions: 'user-guide/sending-transaction.md'
  - Advanced Guide:
      - QRcode provider: 'advanced-guide/qrcode-provider.md'
      - Customizing texts: 'advanced-guide/customizing-texts.md'
      - Customizing buttons: 'advanced-guide/customizing-buttons.md'
      - Multilanguage support: 'advanced-guide/multilanguage-support.md'

extra:
  analytics:
    provider: google
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nessshon
    - icon: fontawesome/brands/telegram
      link: https://t.me/nessshon
